refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "[{l}] {m}{n}"
  tests:
    kind: file
    path: "log/tests.log"
    encoder:
      pattern: "{d}: [{l}] {m}{n}"
root:
  level: warn
  appenders:
    - tests
# loggers:
  # level: info